- name: ALLISONS Windows Updates Proto-Type Testing 
  hosts: ALLISONS-All-Servers
  remote_user: AnsibleService
#  become: yes
#  gather_facts: false

    
  tasks:
    - name: perform updates on the server
      ansible.windows.win_updates:
         category_names:
            - CriticalUpdates
            - SecurityUpdates
         state: searched
         register: update_res
